### ISSUE TITLE
VectorscopeCC does not apply to detailers (impact pack)

### ISSUE THREAD

**Issue by IdeaFridge** [pamparamm/ComfyUI-vectorscope-cc#5]
![image](https://github.com/user-attachments/assets/00d44eaf-1b7c-40ce-81fd-ed86cf93b60d)

First of all, thanks for your great project.

VectorscopeCC works well with all other samplers, but it doesn't seem to work with detailers from the Impact Pack. Although it runs without any errors, the output remains unaffected by the Vectorscope. In fact, bypassing the Vectorscope node gives the same result. Other model modifiers, like freeU_advanced, function as expected. 
Since this is a necessary step, I've tried to resolve the issue on my own, but due to my limited knowledge, I'm having difficulty and seeking some help:)

**Comment by pamparamm** [comment]
Seems like Impact Pack is doing a lot of its own logic during inference. It's the main downside of 'all-in-one god-nodes' - too much effort for providing compatibility.
I'll probably look into that in future, but can't promise anything.

**Comment by IdeaFridge** [comment]
Thank you for your response. I don't mean to put any pressure, but I would be really happy if this issue could be resolved :)

**Comment by IdeaFridge** [comment]
> Seems like Impact Pack is doing a lot of its own logic during inference. It's the main downside of 'all-in-one god-nodes' - too much effort for providing compatibility. I'll probably look into that in future, but can't promise anything.

I checked today, and it looks like the issue has been resolved. It wasn't working a couple of days ago, so the impact pack must have made some adjustments. Glad to see it's fixed!
